// The Node script installed to ~/.schematic/hooks/hook.mjs. CC invokes it
// per event; it reads stdin, POSTs to the daemon, pipes the daemon's
// response to stdout so CC can act on hookSpecificOutput (arch-context).
// If the daemon is unreachable the script exits silently — Schematic is a
// reference tool; it should never break the user's CC session. This
// silence is documented as a deliberate design decision, not a masked
// error (see FALLBACK_AUDIT.md).
//
// Port resolution: read from ~/.schematic/config.json at every invocation
// so `schematic config set port N` takes effect without regenerating this
// script. Cheap — one small fs read per hook fire.

export function generateHookScript(): string {
  return `#!/usr/bin/env node
// Generated by \`schematic install\`. Do not edit by hand.
import http from "node:http";
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

function resolvePort() {
  try {
    const cfg = JSON.parse(readFileSync(join(homedir(), ".schematic", "config.json"), "utf8"));
    if (typeof cfg.port === "number" && cfg.port > 0) return cfg.port;
  } catch { /* fall through to default */ }
  return 7777;
}

const PORT = resolvePort();

let body = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (c) => { body += c; });
process.stdin.on("end", () => {
  const req = http.request({
    hostname: "127.0.0.1",
    port: PORT,
    path: "/hook",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Content-Length": Buffer.byteLength(body),
    },
    timeout: 5000,
  }, (res) => {
    let out = "";
    res.setEncoding("utf8");
    res.on("data", (c) => { out += c; });
    res.on("end", () => {
      // CC reads the hook's stdout as JSON. Pipe the daemon's response directly.
      process.stdout.write(out);
      process.exit(0);
    });
  });
  // Silence network failures — Schematic must never block a CC session.
  req.on("error", () => process.exit(0));
  req.on("timeout", () => {
    req.destroy();
    process.exit(0);
  });
  req.write(body);
  req.end();
});
`;
}
